issuer: http://127.0.0.1:64556/dex

storage:
  type: memory

web:
  http: 127.0.0.1:64556

enablePasswordDB: true

staticClients:
  - id: appauth-test
    secret: appauth-secret
    name: appauth integration test
    redirectURIs:
      - http://127.0.0.1:64557

staticPasswords:
  - email: jane.doe@example.com
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # "password"
    username: jane.doe
    preferredUsername: jane.doe
    userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
    groups:
      - engineering
