name: test-and-build

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - '1.25'
          - '1.26'
          - 'latest'

    defaults:
      run:
        shell: sh

    container:
      image: golang:${{ matrix.go_version }}
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Test code
        run: make test
