name: test-and-build

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - '1.25'
          - '1.26'
          - 'latest'

    defaults:
      run:
        shell: sh

    container:
      image: golang:${{ matrix.go_version }}
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test code
        run: make test
